[features]
seeds = false
[programs.devnet]
zoo_nft_market_solana = "D6oUwPksdxCJLdiJwUUCn6XPGsUXAsXhPdsMfiULPkLa"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ksh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
